'use strict';
/* ============================================================
recruiting-core-v1.js — TalentBase Recruiting Core v1 (PHASE 1.2)

Canonical Recruiting Foundation + Workspace:
- canonical Stage Registry + Internal/Agency pipelines;
- safe legacy adapter: review/shortlist/closed require explicit OWNER/HR resolution;
- Vacancy List/Board use the same CANDIDACIES;
- manual stage selector + desktop drag & drop;
- structured Rejected flow;
- Hired completes only Candidacy and never creates Employee automatically.
============================================================ */
(() => {
if (window.TB_RECRUITING) { console.warn('[TB_RECRUITING] instance already present; Recruiting Core will not create a second one.'); return; }

const CANONICAL_STAGES = [
{key:'new',label:'New profiles',tone:'c-gray',order:0,terminal:false},
{key:'contacted',label:'Contacted',tone:'c-blue',order:1,terminal:false},
{key:'screening',label:'Screening',tone:'c-amber',order:2,terminal:false},
{key:'interview',label:'Interview',tone:'c-blue',order:3,terminal:false},
{key:'client_review',label:'Client Review',tone:'c-violet',order:4,terminal:false},
{key:'client_interview',label:'Client Interview',tone:'c-violet',order:5,terminal:false},
{key:'final_interview',label:'Final Interview',tone:'c-violet',order:6,terminal:false},
{key:'offer',label:'Offer',tone:'c-violet',order:7,terminal:false},
{key:'hiring',label:'Hiring process',tone:'c-blue',order:8,terminal:false},
{key:'hired',label:'Hired',tone:'c-green',order:9,terminal:true},
{key:'rejected',label:'Rejected',tone:'c-red',order:10,terminal:true}
];
const STAGE_INDEX = {};
CANONICAL_STAGES.forEach(s => { STAGE_INDEX[s.key] = Object.freeze(Object.assign({}, s)); });
const RESOLUTION_MARKERS = Object.freeze({
legacy_review:Object.freeze({key:'legacy_review',label:'Legacy review · needs resolution',tone:'c-gray',order:null,terminal:false,needsResolution:true}),
legacy_shortlist:Object.freeze({key:'legacy_shortlist',label:'Legacy shortlist · needs resolution',tone:'c-gray',order:null,terminal:false,needsResolution:true}),
legacy_closed:Object.freeze({key:'legacy_closed',label:'Legacy closed · needs resolution',tone:'c-gray',order:null,terminal:false,needsResolution:true}),
legacy_unknown:Object.freeze({key:'legacy_unknown',label:'Legacy unknown · needs resolution',tone:'c-gray',order:null,terminal:false,needsResolution:true})
});
const INTERNAL_PIPELINE = Object.freeze(['new','contacted','screening','interview','final_interview','offer','hiring','hired']);
const AGENCY_PIPELINE = Object.freeze(['new','contacted','screening','interview','client_review','client_interview','final_interview','offer','hiring','hired']);
const TERMINAL_BRANCH='rejected';
function getPipeline(pipelineType){return (pipelineType==='agency'?AGENCY_PIPELINE:INTERNAL_PIPELINE).slice();}
function vacancyPipelineType(v){return (v&&v.pipelineType==='agency')?'agency':'internal';}
const LEGACY_TO_CANONICAL=Object.freeze({added:'new',interview:'interview',offer:'offer',rejected:'rejected'});
function getCanonicalRecruitingStage(c){
if(!c)return null;const raw=c.stage;
if(typeof raw!=='string'||raw==='')return 'legacy_unknown';
if(raw==='closed')return 'legacy_closed';
if(raw==='review')return 'legacy_review';
if(raw==='shortlist')return 'legacy_shortlist';
if(Object.prototype.hasOwnProperty.call(LEGACY_TO_CANONICAL,raw))return LEGACY_TO_CANONICAL[raw];
if(Object.prototype.hasOwnProperty.call(STAGE_INDEX,raw))return raw;
return 'legacy_unknown';
}
function getStage(key){if(typeof key!=='string'||!key)return null;return STAGE_INDEX[key]||RESOLUTION_MARKERS[key]||null;}
function isLegacyUnresolved(c){const k=getCanonicalRecruitingStage(c);return !!(k&&RESOLUTION_MARKERS[k]);}
function isActiveCandidacy(c){const k=getCanonicalRecruitingStage(c);if(!k||RESOLUTION_MARKERS[k])return false;const s=STAGE_INDEX[k];return !!s&&!s.terminal;}
function stageLabelOf(c){const s=getStage(getCanonicalRecruitingStage(c));return s?s.label:'—';}
function stageChipHTML(c){const s=getStage(getCanonicalRecruitingStage(c));return s?`<span class="chip ${s.tone}">${esc(s.label)}</span>`:'';}
function dotFor(tone){return 'rwd-'+String(tone||'c-gray').replace('c-','');}
function getCandidacyView(c){
if(!c)return null;const canonicalStage=getCanonicalRecruitingStage(c);const marker=RESOLUTION_MARKERS[canonicalStage];const hasText=v=>typeof v==='string'&&v.trim()!== '';
return {id:c.id!=null?c.id:null,profileId:c.profileId!=null?c.profileId:null,vacancyId:c.vacancyId!=null?c.vacancyId:null,rawStage:hasText(c.stage)?c.stage:null,canonicalStage,createdAt:hasText(c.createdAt)?c.createdAt:null,updatedAt:hasText(c.updatedAt)?c.updatedAt:null,stageUpdatedAt:(c.stageUpdatedAt!=null&&c.stageUpdatedAt!=='')?c.stageUpdatedAt:null,score:(typeof c.score==='number'&&Number.isFinite(c.score))?c.score:null,lastAction:(c.lastAction&&typeof c.lastAction==='object')?Object.assign({},c.lastAction):(hasText(c.lastAction)?c.lastAction:null),history:Array.isArray(c.history)?c.history.slice():[],rejection:(c.rejection&&typeof c.rejection==='object'&&!Array.isArray(c.rejection))?Object.assign({},c.rejection):null,needsResolution:!!(marker&&marker.needsResolution)};
}

let rwMode='list',hiredNotice=null,rwAddFor=null,rwAddPick=null,pendingRejectCid=null,rejWho=null;
const CONTACT_VIEW={none:['Не связывались','gray','#9aa4a0'],need:['Нужно связаться','blue','#5b8fd6'],call:['Позвонить','blue','#5b8fd6'],sent:['Написали','blue','#5b8fd6'],waiting:['Ждём ответа','amber','#d99a2b'],dialog:['В диалоге','green','#2fae74'],followup:['Follow-up','amber','#d99a2b'],notint:['Не заинтересован','red','#b06a6c'],nocontact:['Не контактировать','red','#b06a6c']};
function contactChipHTML(p){const cv=CONTACT_VIEW[(p&&p.contactStatus)||'none']||CONTACT_VIEW.none;return `<button type="button" class="cs-chip cs-${cv[1]}" data-open-contact="${p.id}" aria-label="Статус контакта: ${esc(cv[0])}. Изменить"><span class="cs-dot" style="background:${cv[2]}"></span>${esc(cv[0])}</button>`;}
function vacancyCandidacies(v){const cs=candsForVacancy(v.id);return v.aiRan?[...cs].sort((a,b)=>(b.score||0)-(a.score||0)):cs;}
function stageOptionsHTML(v,c){const current=getCanonicalRecruitingStage(c);const unresolved=!!RESOLUTION_MARKERS[current];const keys=getPipeline(vacancyPipelineType(v));let html=unresolved?'<option value="" selected disabled>Выберите стадию…</option>':'';html+=keys.map(k=>{const s=STAGE_INDEX[k];return `<option value="${k}" ${current===k?'selected':''}>${esc(s.label)}</option>`;}).join('');html+=`<option value="rejected" ${current==='rejected'?'selected':''}>${esc(STAGE_INDEX.rejected.label)}</option>`;return html;}
function aiChipHTML(v,c){return (v.aiRan&&typeof c.score==='number'&&Number.isFinite(c.score))?`<span class="chip c-violet"><svg class="ic ic-s"><use href="#i-spark"/></svg>AI ${c.score}</span>`:'<span class="rw-mut">—</span>';}
function legacyRejectedNote(c){return (c.stage==='rejected'&&!c.rejection)?'<div class="rw-warnline">Legacy Rejected: structured rejection details отсутствуют</div>':'';}
function rwListRow(v,c){const p=byId(c.profileId);if(!p)return '';const unresolved=isLegacyUnresolved(c);const upd=c.lastAction?esc(String(c.lastAction)):(c.updatedAt?`<span class="rw-mut">Обновлено:</span> ${esc(c.updatedAt)}`:'<span class="rw-mut">—</span>');return `<div class="rw-row ${unresolved?'rw-row-legacy':''}"><div class="rw-cand"><button type="button" class="rw-cand-id" data-open-profile="${p.id}">${av(p)}<span class="rw-cand-t"><b>${esc(p.name)}</b><span class="rw-sub">${esc(p.headline)}</span></span></button>${legacyRejectedNote(c)}</div><div class="rw-cells"><div class="rw-cell">${contactChipHTML(p)}</div><div class="rw-cell rw-stage-cell">${unresolved?stageChipHTML(c):''}<select class="rw-stage-sel" data-rw-cid="${c.id}" aria-label="Recruiting stage: ${esc(p.name)}">${stageOptionsHTML(v,c)}</select></div><div class="rw-cell">${aiChipHTML(v,c)}</div><div class="rw-cell rw-upd">${upd}</div></div></div>`;}
function rwCard(v,c){const p=byId(c.profileId);if(!p)return '';const unresolved=isLegacyUnresolved(c);const ai=(v.aiRan&&typeof c.score==='number'&&Number.isFinite(c.score))?`<span class="chip c-violet">AI ${c.score}</span>`:'';return `<article class="rw-card" draggable="true" data-rw-card="${c.id}"><button type="button" class="rw-cand-id" data-open-profile="${p.id}">${av(p)}<span class="rw-cand-t"><b>${esc(p.name)}</b><span class="rw-sub">${esc(p.headline)}</span></span></button><div class="rw-card-meta">${contactChipHTML(p)}${unresolved?stageChipHTML(c):''}${ai}</div>${legacyRejectedNote(c)}<select class="rw-stage-sel rw-stage-sel-full" data-rw-cid="${c.id}" aria-label="Recruiting stage: ${esc(p.name)}">${stageOptionsHTML(v,c)}</select></article>`;}
function rwBoard(v){const cs=vacancyCandidacies(v);const keys=getPipeline(vacancyPipelineType(v));const unresolved=cs.filter(isLegacyUnresolved);let cols='';if(unresolved.length){cols+=`<section class="rw-col rw-lane" aria-label="Требует решения"><header class="rw-col-h"><span class="rw-dot rwd-amber"></span><span class="rw-col-t">Требует решения</span><span class="rw-col-c">${unresolved.length}</span></header><div class="rw-col-b">${unresolved.map(c=>rwCard(v,c)).join('')}</div></section>`;}keys.concat(['rejected']).forEach(k=>{const s=STAGE_INDEX[k],items=cs.filter(c=>getCanonicalRecruitingStage(c)===k);cols+=`<section class="rw-col ${k==='rejected'?'rw-col-rej':''}" data-col="${k}" data-drop aria-label="${esc(s.label)}"><header class="rw-col-h"><span class="rw-dot ${dotFor(s.tone)}"></span><span class="rw-col-t">${esc(s.label)}</span><span class="rw-col-c">${items.length}</span></header><div class="rw-col-b">${items.map(c=>rwCard(v,c)).join('')||'<div class="rw-col-empty">—</div>'}</div></section>`;});return `<div class="rw-board">${cols}</div>`;}
function renderRwBody(v){const box=document.querySelector('#rwBody');if(!box)return;const cs=vacancyCandidacies(v),unresolvedN=cs.filter(isLegacyUnresolved).length;let html='';if(hiredNotice&&hiredNotice.vacancyId===v.id)html+=`<div class="rw-notice"><svg class="ic"><use href="#i-check"/></svg><span style="flex:1;min-width:200px">Candidacy завершена как Hired. Employee создаётся отдельным подтверждённым действием.</span><button type="button" class="btn btn-ghost btn-sm" disabled>Создать сотрудника</button></div>`;if(unresolvedN>0)html+=`<div class="rw-notice warn"><svg class="ic"><use href="#i-alert"/></svg><span style="flex:1">Legacy-записи (${unresolvedN}) требуют явного решения OWNER/HR — новый canonical stage назначается вручную.</span></div>`;if(!cs.length)html+='<div class="rw-list"><div class="rw-empty">Кандидатов пока нет. Добавьте профиль к вакансии.</div></div>';else if(rwMode==='list')html+=`<div class="rw-list"><div class="rw-lhead"><span>Кандидат</span><span>Контакт</span><span>Recruiting Stage</span><span>AI</span><span>Обновлено</span></div>${cs.map(c=>rwListRow(v,c)).join('')}</div>`;else html+=rwBoard(v);box.innerHTML=html;const cnt=document.querySelector('#rwCount');if(cnt)cnt.textContent=cs.length+' '+plural(cs.length,'кандидат','кандидата','кандидатов')+' · '+cs.filter(isActiveCandidacy).length+' активных';}
function renderVacancyWorkspace(id){const v=vacById(id);if(!v)return;state.vacancyId=id;const cs=candsForVacancy(id),ptype=vacancyPipelineType(v);$('#vacancyBox').innerHTML=`<button class="back" data-nav="vacancies"><svg class="ic ic-s"><use href="#i-chev-l"/></svg>Вакансии</button><div class="card rw-head"><div class="rw-head-main"><h1 class="rw-title">${esc(v.title)}</h1><div class="rw-meta"><span class="chip ${v.status==='active'?'c-green':'c-gray'}">${v.status==='active'?'Активна':'Пауза'}</span>${dirChipHTML(v.dir)}<span class="chip c-gray">${ptype==='agency'?'Agency pipeline':'Internal pipeline'}</span><span class="rw-subline">${esc(v.city)} · ${esc(v.fmt)} · ${cs.length} ${plural(cs.length,'кандидат','кандидата','кандидатов')}</span></div><p class="rw-desc">${esc(v.desc)}</p></div><div class="rw-head-act"><button type="button" class="btn btn-primary" data-rw-add-open><svg class="ic ic-s"><use href="#i-plus"/></svg>Добавить профиль</button></div></div><div class="rw-toolbar"><div class="seg rw-seg" role="tablist" aria-label="Режим рабочего пространства"><button type="button" data-rw-mode="list" class="${rwMode==='list'?'on':''}">Список</button><button type="button" data-rw-mode="board" class="${rwMode==='board'?'on':''}">Доска</button></div><span class="rw-count" id="rwCount"></span></div><div id="rwBody"></div>${acc('rw-req','Требования',false,`<ul class="req-list">${v.req.map(r=>`<li>${esc(r)}</li>`).join('')}</ul>`,v.req.length)}${acc('rw-notes','Заметки',false,`<div id="vacNotesList">${v.notes.length?v.notes.map(n=>`<div class="note-item">${esc(n.t)}<div class="note-d">${esc(n.d)}</div></div>`).join(''):emptyHtml('Нет заметок')}</div><div class="note-form"><textarea class="input" id="vacNoteText" rows="2" placeholder="Заметка по вакансии…"></textarea><button class="btn btn-primary btn-sm" data-add-vac-note>Добавить</button></div>`,v.notes.length||'')}<section class="acc card w-collapse ai-acc ai-hide"><button class="acc-h" data-toggle><span class="spark-ic"><svg class="ic"><use href="#i-spark"/></svg></span><span class="acc-t">AI-подбор</span><span class="acc-meta">${v.aiRan?'ранжирование выполнено':'не запускалось'}</span><svg class="ic chev"><use href="#i-chev-d"/></svg></button><div class="w-body"><div class="w-inner"><div class="pad"><div class="ai-box"><div class="ai-disc"><svg class="ic ic-s"><use href="#i-spark"/></svg>Результат AI-ранжирования — подсказка, а не решение. Финальный отбор остаётся за человеком.</div><p style="font-size:13px;margin:0 0 10px">Сравнить связанные профили с требованиями вакансии и отсортировать по релевантности.</p><button class="btn btn-ghost btn-sm" data-run-ai="${v.id}"><svg class="ic ic-s"><use href="#i-spark"/></svg>${v.aiRan?'Перезапустить ранжирование':'Запустить ранжирование'}</button></div></div></div></div></section>`;renderRwBody(v);}
renderVacancy=function(id){renderVacancyWorkspace(id);};

function refreshAfterStageChange(){if(state.page==='vacancy'&&state.vacancyId){const v=vacById(state.vacancyId);if(v)renderRwBody(v);}renderVacancies();if(state.page==='home')renderHome();if(state.page==='profile'&&state.profileId)renderProfile(state.profileId);}
function commitCandidacyStageChange(cid,targetKey,opts){const c=CANDIDACIES.find(x=>x.id===cid);if(!c)return false;const stage=STAGE_INDEX[targetKey];if(!stage)return false;const prevKey=getCanonicalRecruitingStage(c),stamp='Сегодня, '+nowTime();c.stage=targetKey;c.updatedAt=stamp;c.stageUpdatedAt=stamp;if(targetKey==='rejected'&&opts&&opts.rejection)c.rejection=opts.rejection;if(!Array.isArray(c.history))c.history=[];let t;if(targetKey==='rejected'&&opts&&opts.rejection)t='Отказ по кандидатуре: '+opts.rejection.who+(opts.rejection.reason?' — '+opts.rejection.reason:'');else{t='Recruiting stage: '+stage.label;if(prevKey&&RESOLUTION_MARKERS[prevKey])t+=' (явное решение по legacy: '+RESOLUTION_MARKERS[prevKey].label+')';}c.history.push({d:stamp,t});if(targetKey==='hired')hiredNotice={vacancyId:c.vacancyId,cid:c.id};refreshAfterStageChange();return true;}
function requestCandidacyStageChange(cid,targetKey){const c=CANDIDACIES.find(x=>x.id===cid);if(!c||!targetKey)return;const cur=getCanonicalRecruitingStage(c);if(cur===targetKey)return;if(targetKey==='rejected'){openRejectDrawer(cid);return;}const v=vacById(c.vacancyId),allowed=getPipeline(vacancyPipelineType(v));if(allowed.indexOf(targetKey)===-1){toast('Стадия недоступна для pipeline этой вакансии','i-alert');return;}if(commitCandidacyStageChange(cid,targetKey,{}))toast('Стадия: '+STAGE_INDEX[targetKey].label);}
function todayInputValue(){const d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');}
function openRejectDrawer(cid){pendingRejectCid=cid;rejWho=null;const c=CANDIDACIES.find(x=>x.id===cid),p=c&&byId(c.profileId),sub=$('#rejectFor');if(sub)sub.textContent=p?('Кандидат: '+p.name):'';$$('#rejectDrawer [data-rej-who]').forEach(b=>b.classList.remove('on'));const r=$('#rejReason');if(r)r.value='';const n=$('#rejNote');if(n)n.value='';const dt=$('#rejDate');if(dt)dt.value=todayInputValue();openDrawer('rejectDrawer');}
function saveRejection(){const c=CANDIDACIES.find(x=>x.id===pendingRejectCid);if(!c){closeDrawers();return;}const reason=($('#rejReason').value||'').trim(),note=($('#rejNote').value||'').trim(),date=$('#rejDate').value;if(!rejWho||!reason||!date){toast('Заполните обязательные поля: кто отказал, причина, дата','i-alert');return;}commitCandidacyStageChange(c.id,'rejected',{rejection:{who:rejWho,reason,note:note||null,date}});pendingRejectCid=null;closeDrawers();toast('Отказ оформлен · Profile не архивирован');}
function renderRwAddList(){const box=document.querySelector('#rwAddList');if(!box)return;const searchEl=document.querySelector('#rwAddSearch'),q=((searchEl&&searchEl.value)||'').trim().toLowerCase(),linked=new Set(candsForVacancy(rwAddFor).map(c=>c.profileId));const rows=PROFILES.filter(p=>!q||((p.name+' '+p.headline+' '+p.role).toLowerCase().indexOf(q)>-1)).map(p=>{const isLinked=linked.has(p.id),right=isLinked?'<span class="chip c-gray">Уже связан</span>':(rwAddPick===p.id?'<span class="chip c-green">Выбран</span>':contactChipHTML(p));return `<div class="rw-add-row"><button type="button" class="rw-cand-id" data-rw-pick="${p.id}" ${isLinked?'disabled':''}>${av(p)}<span class="rw-cand-t"><b>${esc(p.name)}</b><span class="rw-sub">${esc(p.headline)}</span></span></button><span class="rw-add-side">${right}</span></div>`;});box.innerHTML=rows.join('')||emptyHtml('Ничего не найдено');}
function openRwAdd(){rwAddFor=state.vacancyId;rwAddPick=null;const s=$('#rwAddSearch');if(s)s.value='';renderRwAddList();openDrawer('rwAddDrawer');}
function confirmRwAdd(){const v=vacById(rwAddFor),p=byId(rwAddPick);if(!v||!p){toast('Выберите профиль','i-alert');return;}if(CANDIDACIES.some(c=>c.profileId===p.id&&c.vacancyId===v.id)){toast('Профиль уже связан с этой вакансией','i-alert');return;}const stamp='Сегодня, '+nowTime();CANDIDACIES.push({id:'c'+Date.now().toString(36)+Math.floor(Math.random()*9),profileId:p.id,vacancyId:v.id,stage:'new',createdAt:stamp,updatedAt:stamp,stageUpdatedAt:stamp,score:null,lastAction:null,rejection:null,history:[{d:stamp,t:'Добавлен к вакансии · Recruiting stage: New profiles'}]});closeDrawers();toast('Профиль добавлен: '+p.name);if(state.page==='vacancy'&&state.vacancyId===v.id)renderVacancyWorkspace(v.id);renderVacancies();if(state.page==='home')renderHome();}

const toastsEl=document.querySelector('#toasts');
if(toastsEl&&!document.querySelector('#rwAddDrawer'))toastsEl.insertAdjacentHTML('beforebegin',`<aside class="drawer drawer-right" id="rwAddDrawer" aria-label="Добавить профиль к вакансии"><div class="drawer-h"><b>Добавить профиль</b><button class="iconbtn" data-drawer-close aria-label="Закрыть"><svg class="ic"><use href="#i-x"/></svg></button></div><div class="drawer-b"><input class="input" id="rwAddSearch" type="search" placeholder="Поиск профиля…" style="margin-bottom:10px"><div class="rw-add-list" id="rwAddList"></div><p class="form-note">Существующий профиль связывается с вакансией. Новая Candidacy начинается со стадии New profiles. Profile Status и Contact Status не меняются.</p></div><div class="drawer-f"><button class="btn btn-ghost" data-drawer-close>Отмена</button><button class="btn btn-primary" data-rw-add-confirm><svg class="ic ic-s"><use href="#i-check"/></svg>Добавить</button></div></aside><aside class="drawer drawer-right" id="rejectDrawer" aria-label="Отказ по кандидатуре"><div class="drawer-h"><b>Отказ по кандидатуре</b><button class="iconbtn" data-drawer-close aria-label="Закрыть"><svg class="ic"><use href="#i-x"/></svg></button></div><div class="drawer-b"><p class="rw-rej-sub" id="rejectFor"></p><div class="field"><label>Кто отказал *</label><button type="button" class="vpick" data-rej-who="Кандидат"><span class="vp-t">Кандидат</span><span class="pick-check"><svg class="ic"><use href="#i-check"/></svg></span></button><button type="button" class="vpick" data-rej-who="Компания / клиент"><span class="vp-t">Компания / клиент</span><span class="pick-check"><svg class="ic"><use href="#i-check"/></svg></span></button><button type="button" class="vpick" data-rej-who="OWNER / HR"><span class="vp-t">OWNER / HR</span><span class="pick-check"><svg class="ic"><use href="#i-check"/></svg></span></button></div><div class="field"><label for="rejReason">Причина *</label><textarea class="input" id="rejReason" rows="2" placeholder="Причина отказа…"></textarea></div><div class="field"><label for="rejNote">Заметка</label><input class="input" id="rejNote" placeholder="Необязательно"></div><div class="field"><label for="rejDate">Дата *</label><input class="input" id="rejDate" type="date"></div><p class="form-note">Rejected относится только к этой Candidacy: Profile не архивируется, Contact Status не меняется.</p></div><div class="drawer-f"><button class="btn btn-ghost" data-rej-cancel>Отмена</button><button class="btn btn-primary" data-rej-save><svg class="ic ic-s"><use href="#i-check"/></svg>Сохранить</button></div></aside>`);
const rwAddSearchEl=document.querySelector('#rwAddSearch');if(rwAddSearchEl)rwAddSearchEl.addEventListener('input',()=>renderRwAddList());

document.addEventListener('click',e=>{const mode=e.target.closest('[data-rw-mode]');if(mode){rwMode=mode.dataset.rwMode;$$('.rw-seg [data-rw-mode]').forEach(b=>b.classList.toggle('on',b.dataset.rwMode===rwMode));const v=vacById(state.vacancyId);if(v&&state.page==='vacancy')renderRwBody(v);return;}if(e.target.closest('[data-rw-add-open]')){openRwAdd();return;}const pick=e.target.closest('[data-rw-pick]');if(pick&&!pick.disabled){rwAddPick=pick.dataset.rwPick;renderRwAddList();return;}if(e.target.closest('[data-rw-add-confirm]')){confirmRwAdd();return;}const who=e.target.closest('[data-rej-who]');if(who){rejWho=who.dataset.rejWho;$$('#rejectDrawer [data-rej-who]').forEach(b=>b.classList.toggle('on',b===who));return;}if(e.target.closest('[data-rej-cancel]')){pendingRejectCid=null;closeDrawers();return;}if(e.target.closest('[data-rej-save]')){saveRejection();return;}});
document.addEventListener('change',e=>{const sel=e.target.closest('select.rw-stage-sel');if(sel&&sel.value)requestCandidacyStageChange(sel.dataset.rwCid,sel.value);});
document.addEventListener('dragstart',e=>{const card=e.target.closest&&e.target.closest('[data-rw-card]');if(card){e.dataTransfer.setData('text/plain',card.dataset.rwCard);e.dataTransfer.effectAllowed='move';}});
document.addEventListener('dragover',e=>{const col=e.target.closest&&e.target.closest('.rw-col[data-drop]');if(col){e.preventDefault();col.classList.add('rw-over');}});
document.addEventListener('dragleave',e=>{const col=e.target.closest&&e.target.closest('.rw-col.rw-over');if(col&&!col.contains(e.relatedTarget))col.classList.remove('rw-over');});
document.addEventListener('drop',e=>{const col=e.target.closest&&e.target.closest('.rw-col[data-drop]');if(!col)return;e.preventDefault();col.classList.remove('rw-over');const cid=e.dataTransfer.getData('text/plain');if(cid)requestCandidacyStageChange(cid,col.dataset.col);});

let selfCheckPassed=false;
try{let passed=0,failed=0;const assert=(cond,name)=>{if(cond)passed++;else{failed++;console.error('[TB_RECRUITING] self-check FAILED: '+name);}};[['added','new'],['review','legacy_review'],['shortlist','legacy_shortlist'],['interview','interview'],['offer','offer'],['rejected','rejected'],['closed','legacy_closed'],['unknown','legacy_unknown']].forEach(pair=>{const iso={id:'iso-map',stage:pair[0]};assert(getCanonicalRecruitingStage(iso)===pair[1],'mapping '+pair[0]+' -> '+pair[1]);assert(iso.stage===pair[0],'adapter must not mutate '+pair[0]);});assert(getCanonicalRecruitingStage({stage:'closed'})!=='hired','closed !== hired');assert(getCanonicalRecruitingStage({stage:'review'})!=='screening','review !== screening');assert(getCanonicalRecruitingStage({stage:'shortlist'})!=='interview','shortlist !== interview');assert(CANONICAL_STAGES.length===11,'11 canonical stages');assert(getPipeline().join(',')==='new,contacted,screening,interview,final_interview,offer,hiring,hired','internal pipeline');const ag=getPipeline('agency');assert(ag.includes('client_review')&&ag.includes('client_interview'),'agency client stages');const sparse=getCandidacyView({id:'x',stage:'review'});assert(sparse.stageUpdatedAt===null&&sparse.rejection===null&&Array.isArray(sparse.history),'safe sparse view');selfCheckPassed=failed===0;console.info('[TB_RECRUITING] Recruiting Core self-check: '+passed+' passed, '+failed+' failed');}catch(err){console.error('[TB_RECRUITING] self-check crashed (app not affected)',err);}

window.TB_RECRUITING=Object.freeze({version:'2.0.0-recruiting-core-v1',stages:Object.freeze(CANONICAL_STAGES.map(s=>STAGE_INDEX[s.key])),getStage,getPipeline,vacancyPipelineType,getCanonicalRecruitingStage,getCandidacyView,isLegacyUnresolved,isActiveCandidacy,stageLabelOf,stageChipHTML,terminalBranch:TERMINAL_BRANCH,requestCandidacyStageChange,commitCandidacyStageChange,selfCheckPassed});

/* Compatibility with the preserved base-v1 source. These are presentation/runtime adapters only; source fixtures are not rewritten. */
vacsBodyHTML=function(p){const cs=candsForProfile(p.id);if(!cs.length)return emptyHtml('Профиль не связан с вакансиями');return cs.map(c=>{const v=vacById(c.vacancyId);return `<div class="cvac-row"><button class="cvac-main" data-open-vacancy="${v.id}"><span class="cvac-t">${esc(v.title)}</span><span class="cvac-s">связь: ${esc(c.createdAt)} · ${esc(dirName(v.dir))}</span></button>${stageChipHTML(c)}</div>`;}).join('');};
renderVacancies=function(){const act=VACANCIES.filter(v=>v.status==='active').length;$('#vacCount').textContent=VACANCIES.length+' '+plural(VACANCIES.length,'вакансия','вакансии','вакансий')+' · '+act+' активные';$('#vacList').innerHTML=VACANCIES.map(v=>{const cs=candsForVacancy(v.id),actN=cs.filter(isActiveCandidacy).length;return `<button class="vrow" data-open-vacancy="${v.id}"><span class="v-ic"><svg class="ic"><use href="#i-briefcase"/></svg></span><span class="v-main"><span class="v-title">${esc(v.title)}</span><span class="v-meta">${esc(v.city)} · ${cs.length} ${plural(cs.length,'кандидат','кандидата','кандидатов')} · ${actN} активных</span></span>${dirChipHTML(v.dir)}<span class="chip ${v.status==='active'?'c-green':'c-gray'}">${v.status==='active'?'Активна':'Пауза'}</span><span style="color:var(--text3)"><svg class="ic ic-s"><use href="#i-chev-r"/></svg></span></button>`;}).join('');};
const preRecruitingRenderHome=renderHome;
renderHome=function(){preRecruitingRenderHome();const acts=CANDIDACIES.filter(isActiveCandidacy);const cnt=$('#cntAct');if(cnt)cnt.textContent=acts.length;const box=$('#homeActions');if(box)box.innerHTML=acts.length?acts.map(c=>{const p=byId(c.profileId),v=vacById(c.vacancyId);return `<button class="prow" data-open-vacancy="${c.vacancyId}">${av(p)}<span class="p-main"><span class="p-name">${esc(p.name)}</span><span class="p-head">${esc(v.title)}</span></span>${stageChipHTML(c)}</button>`;}).join(''):emptyHtml('Активных recruiting-действий нет');const hv=$('#homeVacs');if(hv){const actVacs=VACANCIES.filter(v=>v.status==='active');hv.innerHTML=actVacs.map(v=>{const cs=candsForVacancy(v.id),actN=cs.filter(isActiveCandidacy).length;return `<button class="vrow" data-open-vacancy="${v.id}"><span class="v-ic"><svg class="ic"><use href="#i-briefcase"/></svg></span><span class="v-main"><span class="v-title">${esc(v.title)}</span><span class="v-meta">${esc(dirName(v.dir))} · ${cs.length} ${plural(cs.length,'кандидат','кандидата','кандидатов')} · ${actN} активных</span></span><span class="chip ${v.status==='active'?'c-green':'c-gray'}">${v.status==='active'?'Активна':'Пауза'}</span></button>`;}).join('')||emptyHtml('Активных вакансий нет');}};
exportCSV=function(){const rows=[['Имя','Роль','Направления','Локация','Источник','Статус профиля','Статус контакта','Подтверждённость','Вакансии']];const contactLabels={none:'Не связывались',need:'Нужно связаться',call:'Позвонить',sent:'Написали',waiting:'Ждём ответа',dialog:'В диалоге',followup:'Follow-up',notint:'Не заинтересован',nocontact:'Не контактировать'};PROFILES.forEach(p=>rows.push([p.name,p.headline,p.directions.map(dirName).join('; '),p.location,p.source,STATE_LABEL[p.state],contactLabels[p.contactStatus||'none']||'Не связывались',p.verify,candsForProfile(p.id).map(c=>{const v=vacById(c.vacancyId);return (v?v.title:'Вакансия')+' ('+stageLabelOf(c)+')';}).join('; ')]));const csv=rows.map(r=>r.map(x=>'"'+String(x).replaceAll('"','""')+'"').join(';')).join('\r\n');const blob=new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='talentbase-profiles.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast('CSV с профилями выгружен','i-download');};

renderVacancies();renderHome();if(state.page==='vacancy'&&state.vacancyId)renderVacancyWorkspace(state.vacancyId);if(state.page==='profile'&&state.profileId)renderProfile(state.profileId);
console.info('[TB_RECRUITING] Recruiting Core v1 ready · legacy business facts preserved');
})();
